name: Sync docs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    name: 同步到 website 仓库
    runs-on: ubuntu-latest
    steps:
      - name: 检出源仓库
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取所有历史记录，避免浅克隆问题

      - name: 配置 SSH
        run: |
          # 安装私钥
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # 将 GitHub.com 添加到已知主机（避免首次连接提示）
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          # 可选：测试连接
          ssh -T git@github.com || true # 忽略退出代码，测试连接是否正常工作

      - name: 配置 Git 用户信息
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: 克隆文档网站仓库
        run: |
          git clone --depth=1 git@github.com:uni-helper/website.git /tmp/website-repo

      - name: 删除旧文档
        run: |
          # 删除源仓库的 md 文件
          find /tmp/website-repo/content/uni-use -name "*.md" -exec rm -f {} \; 2>/dev/null || true
          # 移除空目录
          find /tmp/website-repo/content/uni-use -type d -empty -delete 2>/dev/null || true

      - name: 复制 src 下的 .md 文件
        run: |
          cd src
          # 复制 src 目录下的所有 .md 文件
          find . -name "*.md" -exec cp -f --parents {} /tmp/website-repo/content/uni-use \; 2>/dev/null || true
          # 复制 src/index.md 文件
          cp -f index.md /tmp/website-repo/content/uni-use/apis.md

      - name: 复制 docs 下的 .md 文件
        run: |
          cd docs
          # 复制 docs 目录下的所有 .md 文件
          find . -name "*.md" -exec cp -f --parents {} /tmp/website-repo/content/uni-use \; 2>/dev/null || true

      - name: 提交并推送更改
        run: |
          cd /tmp/website-repo
          git add .

          # 检查是否有更改需要提交
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Automated update from $GITHUB_REPOSITORY@$GITHUB_SHA"
            git push origin main
          fi

      - name: 清理文件
        run: |
          rm -rf /tmp/website-repo
          rm -f ~/.ssh/id_ed25519
